# Generated by Django 6.0.7 on 2026-07-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_seed_analysis_services'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=120)),
                ('title_fa', models.CharField(max_length=120)),
                ('description_en', models.TextField()),
                ('description_fa', models.TextField()),
                ('hero_media_url', models.URLField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'title_en'),
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='website.componentpage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.headermenuitem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='analytics.analysisservice')),
            ],
            options={
                'ordering': ('display_order', 'title_en'),
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('doc_id', models.CharField(max_length=50, unique=True)),
                ('title_en', models.CharField(max_length=180)),
                ('title_fa', models.CharField(max_length=180)),
                ('description_en', models.TextField()),
                ('description_fa', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('hero_title_en', models.CharField(max_length=180)),
                ('hero_title_fa', models.CharField(max_length=180)),
                ('hero_media_url', models.URLField(blank=True)),
                ('get_started_title_en', models.CharField(default='Ready to get started?', max_length=180)),
                ('get_started_title_fa', models.CharField(default='آماده شروع هستید؟', max_length=180)),
                ('is_published', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_page', to='analytics.analysisservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=160)),
                ('title_fa', models.CharField(max_length=160)),
                ('description_en', models.TextField()),
                ('description_fa', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='website.servicepage')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
