# Generated by Django 6.0.7 on 2026-07-19 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fa', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('result_kind', models.CharField(choices=[('RFM', 'RFM'), ('BASKET', 'Market basket'), ('PREDICTIVE', 'Predictive')], max_length=15)),
                ('required_mapping_fields', models.JSONField(default=list)),
                ('optional_mapping_fields', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('raw_file_path', models.FileField(upload_to='uploads/')),
                ('data_mapping', models.JSONField(default=dict)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='analytics.analysisservice')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WaitlistLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BasketResult',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basket_result', serialize=False, to='analytics.project')),
                ('rules', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MLResult',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ml_result', serialize=False, to='analytics.project')),
                ('metrics', models.JSONField(default=dict)),
                ('visualization_data', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RFMResult',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rfm_result', serialize=False, to='analytics.project')),
                ('summary', models.JSONField(default=dict)),
                ('chart_data', models.JSONField(default=list)),
                ('actionable_insights', models.JSONField(default=list)),
                ('result_file_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
