# Generated by Django 6.0.7 on 2026-07-21 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="engine_version",
            field=models.CharField(default="1.0.0", max_length=30),
        ),
        migrations.AddField(
            model_name="project",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("file", models.FileField(upload_to="datasets/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("row_count", models.PositiveBigIntegerField(blank=True, null=True)),
                ("detected_columns", models.JSONField(default=list)),
                ("validation_status", models.CharField(choices=[("PENDING", "Pending"), ("VALID", "Valid"), ("INVALID", "Invalid")], default="PENDING", max_length=10)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="project",
            name="dataset",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="analytics.dataset"),
        ),
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("stage", models.CharField(choices=[("CREATED", "Created"), ("MAPPING", "Input mapping"), ("QUEUED", "Queued"), ("LOADING", "Loading dataset"), ("EXECUTING", "Executing engine"), ("PERSISTING", "Persisting output"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], max_length=15)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="analytics.project")),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["user", "validation_status"], name="analytics_d_user_id_c8aa21_idx"),
        ),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(fields=["run", "created_at"], name="analytics_r_run_id_92ee41_idx"),
        ),
    ]
