# Generated by Django 6.0.7 on 2026-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_project_completed_at_project_engine_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runevent',
            name='stage',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MAPPING', 'Input mapping'), ('QUEUED', 'Queued'), ('LOADING', 'Loading dataset'), ('PREPROCESSING', 'Preprocessing'), ('FEATURE_ENGINEERING', 'Feature engineering'), ('MODEL_EXECUTION', 'Model execution'), ('EVALUATING', 'Evaluating output'), ('RESULT_GENERATION', 'Generating result'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
