# Generated by Django 6.0.7 on 2026-07-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_project_status'),
        ('developer_api', '0002_seed_trial_api_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=120)),
                ('title_fa', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=180)),
                ('title_fa', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_fa', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_pages', to='analytics.analysisservice')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='developer_api.documentationsection')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('STEPS', 'Numbered steps'), ('CODE', 'Code example'), ('SCHEMA', 'CSV schema'), ('REPORT', 'Report explanation'), ('CALLOUT', 'Callout')], default='TEXT', max_length=12)),
                ('heading_en', models.CharField(blank=True, max_length=180)),
                ('heading_fa', models.CharField(blank=True, max_length=180)),
                ('content_en', models.TextField(blank=True)),
                ('content_fa', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=30)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='developer_api.documentationpage')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
