from django.db import migrations


SECTIONS = (
    ("start-here", "Start Here", "شروع از اینجا", 1),
    ("guides", "Guides", "راهنماها", 2),
    ("analytics-services", "Analytics Services", "سرویس‌های تحلیلی", 3),
    ("api-reference", "API Reference", "مرجع API", 4),
    ("operations", "Operations", "عملیات و پشتیبانی", 5),
)

GENERAL_PAGES = (
    ("start-here", "introduction", "Introduction", "معرفی", "Build repeatable commerce analytics workflows with the InsightFlow dashboard or API.", "با داشبورد یا API اینسایت‌فلو، فرایندهای تحلیل تجارت را به‌شکل تکرارپذیر اجرا کنید.", [
        ("TEXT", "What you can build", "چه چیزی می‌توانید بسازید", "Upload transaction data, map business columns, run an analytics engine asynchronously, and consume decision-ready reports. The same project workflow is available in the customer dashboard and through authenticated API requests.", "داده‌های تراکنش را بارگذاری کنید، ستون‌های کسب‌وکار را نگاشت کنید، موتور تحلیل را به‌صورت غیرهمزمان اجرا کنید و گزارش‌های آماده تصمیم‌گیری دریافت کنید. همین فرایند هم در داشبورد و هم از طریق API احراز هویت‌شده در دسترس است.", "", ""),
        ("STEPS", "The standard workflow", "فرایند استاندارد", "Authenticate and create an API key\nChoose an analytics service\nUpload a CSV, XLS, or XLSX file\nMap detected columns to required fields\nStart the project and poll its status\nRead or export the completed report", "احراز هویت کنید و کلید API بسازید\nیک سرویس تحلیلی انتخاب کنید\nفایل CSV یا XLS یا XLSX بارگذاری کنید\nستون‌های شناسایی‌شده را به فیلدهای ضروری نگاشت کنید\nپروژه را اجرا و وضعیت آن را پیگیری کنید\nگزارش تکمیل‌شده را مشاهده یا دریافت کنید", "", ""),
        ("CALLOUT", "Data safety", "امنیت داده", "Keep API keys on your server. Never place a live key in browser JavaScript, a mobile binary, a public repository, or a shared spreadsheet.", "کلید API را فقط در سرور نگهداری کنید. هرگز کلید زنده را در جاوااسکریپت مرورگر، برنامه موبایل، مخزن عمومی یا فایل اشتراکی قرار ندهید.", "", ""),
    ]),
    ("start-here", "getting-started", "Getting Started", "شروع سریع", "Run your first analysis from authentication to report retrieval.", "اولین تحلیل خود را از احراز هویت تا دریافت گزارش اجرا کنید.", [
        ("STEPS", "Before you begin", "پیش از شروع", "Create or sign in to your account with phone and OTP\nComplete the business profile\nCreate an API key from Developer API\nPrepare a UTF-8 CSV with a header row\nConfirm that at least one analysis credit is available", "با شماره موبایل و رمز یک‌بارمصرف وارد شوید\nپروفایل کسب‌وکار را تکمیل کنید\nاز بخش رابط برنامه‌نویسی یک کلید API بسازید\nیک فایل CSV با UTF-8 و ردیف عنوان آماده کنید\nاز وجود حداقل یک اعتبار تحلیل مطمئن شوید", "", ""),
        ("CODE", "Check available services", "بررسی سرویس‌های موجود", "List the service catalog before creating a project. Active services can run immediately; beta services accept private-review requests.", "پیش از ساخت پروژه، فهرست سرویس‌ها را دریافت کنید. سرویس‌های فعال بلافاصله اجرا می‌شوند و سرویس‌های بتا درخواست بررسی خصوصی می‌پذیرند.", "curl http://localhost:8000/api/v1/services/ \\\n+  -H \"X-API-Key: $MLAAS_API_KEY\"", "bash"),
    ]),
    ("guides", "authentication", "Authentication", "احراز هویت", "Sign in with phone and OTP, then use JWT for account management.", "با شماره موبایل و رمز یک‌بارمصرف وارد شوید و برای مدیریت حساب از JWT استفاده کنید.", [
        ("CODE", "Request an OTP", "درخواست رمز یک‌بارمصرف", "Send the phone number in international format.", "شماره موبایل را با فرمت بین‌المللی ارسال کنید.", "curl -X POST http://localhost:8000/api/v1/auth/send-otp/ \\\n+  -H \"Content-Type: application/json\" \\\n+  -d '{\"phone_number\":\"+989121234567\"}'", "bash"),
        ("CODE", "Verify and receive tokens", "تأیید و دریافت توکن", "The response contains access and refresh tokens. Access tokens authorize dashboard account operations.", "پاسخ شامل توکن دسترسی و توکن تازه‌سازی است. توکن دسترسی عملیات حساب داشبورد را مجاز می‌کند.", "curl -X POST http://localhost:8000/api/v1/auth/verify-otp/ \\\n+  -H \"Content-Type: application/json\" \\\n+  -d '{\"phone_number\":\"+989121234567\",\"otp_code\":\"123456\"}'", "bash"),
        ("CALLOUT", "Production OTP", "رمز یک‌بارمصرف در محیط واقعی", "The fixed development OTP must be replaced by the configured SMS provider before production launch.", "پیش از انتشار نهایی، رمز ثابت محیط توسعه باید با ارائه‌دهنده پیامک پیکربندی‌شده جایگزین شود.", "", ""),
    ]),
    ("guides", "api-keys", "API Keys & Authorization", "کلیدهای API و مجوزها", "Create, store, rotate, and revoke server-to-server credentials safely.", "اعتبارنامه‌های سرور به سرور را به‌صورت امن بسازید، نگهداری، تعویض و لغو کنید.", [
        ("STEPS", "Key lifecycle", "چرخه عمر کلید", "Create a named key in the dashboard\nCopy the secret immediately because it is shown once\nStore it in a secret manager or protected environment variable\nSend it through the X-API-Key header\nRotate keys periodically and revoke unused credentials", "یک کلید نام‌گذاری‌شده در داشبورد بسازید\nکلید محرمانه را همان لحظه کپی کنید چون فقط یک‌بار نمایش داده می‌شود\nآن را در مدیر اسرار یا متغیر محیطی محافظت‌شده نگهداری کنید\nکلید را در هدر X-API-Key ارسال کنید\nکلیدها را دوره‌ای تعویض و موارد بدون استفاده را لغو کنید", "", ""),
        ("CODE", "Authorize a request", "ارسال درخواست مجاز", "API keys identify the owning customer, plan, allowed endpoints, service access, and request quota.", "کلید API مالک حساب، طرح، مسیرهای مجاز، دسترسی سرویس و سهمیه درخواست را مشخص می‌کند.", "curl http://localhost:8000/api/v1/dashboard/ \\\n+  -H \"X-API-Key: $MLAAS_API_KEY\"", "bash"),
    ]),
    ("guides", "file-upload", "File Upload & Column Mapping", "بارگذاری فایل و نگاشت ستون‌ها", "Prepare files that validate correctly and map source columns without ambiguity.", "فایل‌هایی آماده کنید که درست اعتبارسنجی شوند و ستون‌های منبع را بدون ابهام نگاشت کنند.", [
        ("SCHEMA", "Universal file rules", "قواعد عمومی فایل", "Use CSV, XLS, or XLSX. Include exactly one header row. Required columns cannot be empty. Dates should use ISO 8601. Amount and quantity fields must be numeric. Keep identifiers consistent as strings.", "از CSV یا XLS یا XLSX استفاده کنید. فایل باید دقیقاً یک ردیف عنوان داشته باشد. ستون‌های ضروری نباید خالی باشند. تاریخ‌ها بهتر است ISO 8601 باشند. مبلغ و تعداد باید عددی باشند. شناسه‌ها را به‌صورت رشته سازگار نگه دارید.", "customer_id,invoice_id,invoice_date,total_amount\nC-1001,INV-5001,2026-07-01,129.90", "csv"),
        ("CODE", "Upload a project", "بارگذاری پروژه", "The response returns a project ID and detected columns. Uploading does not consume an analysis credit.", "پاسخ شامل شناسه پروژه و ستون‌های شناسایی‌شده است. بارگذاری فایل اعتبار تحلیل مصرف نمی‌کند.", "curl -X POST http://localhost:8000/api/v1/projects/upload/ \\\n+  -H \"X-API-Key: $MLAAS_API_KEY\" \\\n+  -F \"file=@transactions.csv\" \\\n+  -F \"title=July customer analysis\" \\\n+  -F \"analysis_type=RFM\"", "bash"),
    ]),
    ("guides", "project-lifecycle", "Project Lifecycle", "چرخه عمر پروژه", "Understand pending, processing, successful, failed, and waitlisted projects.", "وضعیت‌های در انتظار، در حال پردازش، موفق، ناموفق و فهرست بتا را بشناسید.", [
        ("TEXT", "Statuses", "وضعیت‌ها", "PENDING means the file is uploaded and mapping can continue. PROCESSING means a credit was consumed and Celery is running the engine. SUCCESS means the report is ready. FAILED includes an error message. WAITLISTED means a private-beta request was registered and consumes no credit.", "PENDING یعنی فایل بارگذاری شده و نگاشت قابل ادامه است. PROCESSING یعنی یک اعتبار مصرف شده و Celery موتور را اجرا می‌کند. SUCCESS یعنی گزارش آماده است. FAILED شامل پیام خطاست. WAITLISTED یعنی درخواست بتای خصوصی ثبت شده و اعتباری مصرف نمی‌شود.", "", ""),
        ("CODE", "Poll project status", "پیگیری وضعیت پروژه", "Poll every few seconds until the project reaches a terminal status. Avoid aggressive polling.", "هر چند ثانیه وضعیت را بررسی کنید تا پروژه به وضعیت نهایی برسد. از درخواست‌های بسیار پرتکرار خودداری کنید.", "curl http://localhost:8000/api/v1/projects/$PROJECT_ID/status/ \\\n+  -H \"X-API-Key: $MLAAS_API_KEY\"", "bash"),
    ]),
    ("guides", "reading-reports", "Reading Reports", "خواندن گزارش‌ها", "Interpret KPIs, charts, detailed rows, and recommended actions responsibly.", "شاخص‌ها، نمودارها، ردیف‌های تفصیلی و اقدامات پیشنهادی را درست تفسیر کنید.", [
        ("REPORT", "Report anatomy", "ساختار گزارش", "Summary metrics describe the population or model output. Charts highlight distribution or ranking. Detailed rows preserve the values used in the visualization. Recommended actions translate findings into experiments, not guaranteed outcomes.", "شاخص‌های خلاصه جامعه یا خروجی مدل را توضیح می‌دهند. نمودارها توزیع یا رتبه‌بندی را نشان می‌دهند. ردیف‌های تفصیلی مقادیر نمودار را نگه می‌دارند. اقدامات پیشنهادی یافته‌ها را به آزمایش کسب‌وکاری تبدیل می‌کنند و نتیجه قطعی نیستند.", "", ""),
        ("CALLOUT", "Responsible use", "استفاده مسئولانه", "Validate important decisions with business context, data-quality checks, and controlled experiments. Model outputs should support—not replace—human judgment.", "تصمیم‌های مهم را با زمینه کسب‌وکار، بررسی کیفیت داده و آزمایش کنترل‌شده اعتبارسنجی کنید. خروجی مدل باید پشتیبان قضاوت انسانی باشد، نه جایگزین آن.", "", ""),
    ]),
    ("api-reference", "errors-and-limits", "Errors, Quotas & Rate Limits", "خطاها، سهمیه‌ها و محدودیت نرخ", "Handle validation, authorization, quota, and processing failures predictably.", "خطاهای اعتبارسنجی، مجوز، سهمیه و پردازش را به‌شکل قابل پیش‌بینی مدیریت کنید.", [
        ("TEXT", "Common HTTP responses", "پاسخ‌های رایج HTTP", "400 indicates invalid input or mapping. 401 means authentication failed. 403 means the plan or endpoint policy denies access. 402 means no analysis credit remains. 409 indicates a conflicting project state. 429 means the monthly API quota is exhausted.", "کد 400 یعنی ورودی یا نگاشت نامعتبر است. 401 یعنی احراز هویت شکست خورده است. 403 یعنی طرح یا سیاست مسیر اجازه دسترسی نمی‌دهد. 402 یعنی اعتبار تحلیل باقی نمانده است. 409 یعنی وضعیت پروژه با عملیات تعارض دارد. 429 یعنی سهمیه ماهانه API تمام شده است.", "", ""),
        ("CODE", "Rate-limit headers", "هدرهای محدودیت نرخ", "Successful API-key requests include the plan limit and remaining request count.", "درخواست‌های موفق با کلید API شامل سقف طرح و تعداد درخواست باقی‌مانده هستند.", "X-RateLimit-Limit: 1000\nX-RateLimit-Remaining: 942", "http"),
    ]),
    ("operations", "admin-management", "Managing Documentation", "مدیریت مستندات", "Publish and reorder documentation from Django admin without deploying code.", "مستندات را بدون انتشار کد از پنل مدیریت منتشر و مرتب کنید.", [
        ("STEPS", "Admin workflow", "فرایند مدیریت", "Open Django admin and select Documentation sections\nCreate or reorder navigation groups\nCreate bilingual documentation pages\nAttach a service when the page documents an analytics engine\nAdd text, steps, schema, code, report, or callout blocks\nPreview the public docs and then activate the page", "پنل مدیریت جنگو را باز و بخش‌های مستندات را انتخاب کنید\nگروه‌های ناوبری را بسازید یا مرتب کنید\nصفحه مستندات دوزبانه ایجاد کنید\nبرای مستند موتور تحلیل، سرویس مرتبط را انتخاب کنید\nبلوک متن، مراحل، ساختار، کد، گزارش یا نکته اضافه کنید\nمستند عمومی را بررسی و سپس صفحه را فعال کنید", "", ""),
    ]),
)

SERVICES = (
    ("RFM", "rfm-segmentation", "RFM Segmentation", "بخش‌بندی RFM", True, "customer_id,invoice_date,invoice_id,total_amount", "customer_id_column, date_column, invoice_id_column; amount_column is optional.", "ستون شناسه مشتری، تاریخ و شناسه فاکتور ضروری است؛ ستون مبلغ اختیاری است.", "The report shows total customers, churn-risk percentage, repeat-buyer percentage, segment distribution, and a recommended action for every segment.", "گزارش تعداد مشتریان، درصد ریسک ریزش، درصد خریداران تکراری، توزیع بخش‌ها و اقدام پیشنهادی هر بخش را نشان می‌دهد."),
    ("MARKET_BASKET", "market-basket", "Market Basket Analysis", "تحلیل سبد خرید", True, "invoice_id,product_name,product_category,quantity", "invoice_id_column and product_name_column are required; category and quantity are optional.", "شناسه فاکتور و نام محصول ضروری است؛ دسته‌بندی و تعداد اختیاری است.", "The report ranks product-to-product rules by lift and confidence and includes support, average confidence, and the strongest lift.", "گزارش ارتباط محصول به محصول را بر اساس لیفت و اطمینان رتبه‌بندی می‌کند و فراوانی، میانگین اطمینان و بیشترین لیفت را نشان می‌دهد."),
    ("PROPENSITY", "purchase-propensity", "Purchase Propensity", "احتمال خرید", True, "customer_id,invoice_date,invoice_amount", "customer_id_column, date_column, and amount_column are required.", "شناسه مشتری، تاریخ و مبلغ ضروری هستند.", "The report shows customers scored, model diagnostics, and a ranked 0–100 purchase-propensity score for each returned customer.", "گزارش تعداد مشتریان امتیازدهی‌شده، شاخص‌های مدل و امتیاز احتمال خرید صفر تا صد را برای مشتریان نشان می‌دهد."),
    ("ANOMALY", "sales-anomaly", "Sales Anomaly Detection", "تشخیص ناهنجاری فروش", True, "invoice_id,invoice_date,total_amount", "invoice_id_column, date_column, and amount_column are required. At least ten complete transactions are needed.", "شناسه فاکتور، تاریخ و مبلغ ضروری هستند و حداقل ده تراکنش کامل لازم است.", "The report shows transactions checked, anomalies found, flagged invoice amounts, timestamps, source rows, and anomaly scores.", "گزارش تعداد تراکنش‌های بررسی‌شده، ناهنجاری‌ها، مبلغ فاکتورهای علامت‌خورده، زمان، ردیف منبع و امتیاز ناهنجاری را نشان می‌دهد."),
    ("CHURN", "customer-churn", "Customer Churn Audit", "تحلیل ریزش مشتری", False, "customer_id,last_purchase_date,purchase_count,total_spend,engagement_rate,churned", "The beta schema uses customer activity, value, engagement, and an optional historical churn label.", "ساختار بتا از فعالیت، ارزش، تعامل و برچسب تاریخی اختیاری ریزش استفاده می‌کند.", "The planned report contains churn-risk cohorts, contributing signals, and intervention priorities.", "گزارش برنامه‌ریزی‌شده شامل گروه‌های ریسک ریزش، عوامل اثرگذار و اولویت‌های مداخله است."),
    ("CLV", "customer-lifetime-value", "Customer Lifetime Value", "ارزش طول عمر مشتری", False, "customer_id,invoice_id,invoice_date,total_amount,acquisition_channel", "The beta schema requires customer-level transaction history and monetary value.", "ساختار بتا به تاریخچه تراکنش مشتری و ارزش پولی نیاز دارد.", "The planned report contains predicted lifetime-value bands, customer rankings, and confidence ranges.", "گزارش برنامه‌ریزی‌شده شامل سطوح ارزش طول عمر، رتبه‌بندی مشتری و بازه اطمینان است."),
    ("PRODUCT_SHARE", "product-share", "Product Share Matrix", "ماتریس سهم محصول", False, "invoice_date,product_id,product_name,product_category,quantity,total_amount", "The beta schema requires dated product sales with quantity and revenue.", "ساختار بتا به فروش تاریخ‌دار محصول همراه با تعداد و درآمد نیاز دارد.", "The planned report shows category mix, product contribution, concentration, and trend changes.", "گزارش برنامه‌ریزی‌شده ترکیب دسته‌ها، سهم محصول، تمرکز و تغییرات روند را نشان می‌دهد."),
    ("DEMAND_FORECAST", "demand-forecast", "Demand Forecasting", "پیش‌بینی تقاضا", False, "date,product_id,units_sold,unit_price,inventory_level,promotion_active,holiday", "The beta schema requires a regular product-level time series with demand drivers.", "ساختار بتا به سری زمانی منظم محصول همراه با عوامل تقاضا نیاز دارد.", "The planned report includes demand forecasts, confidence bands, seasonality, and stock-risk windows.", "گزارش برنامه‌ریزی‌شده شامل پیش‌بینی تقاضا، بازه اطمینان، فصل‌پذیری و دوره‌های ریسک موجودی است."),
    ("RECOMMENDER", "personalized-recommender", "Personalized Recommender", "پیشنهادگر شخصی‌سازی‌شده", False, "customer_id,product_id,interaction_type,interaction_date,quantity,rating", "The beta schema accepts customer-product views, carts, purchases, and optional ratings.", "ساختار بتا بازدید، سبد، خرید و امتیاز اختیاری مشتری-محصول را می‌پذیرد.", "The planned report returns ranked product recommendations per customer with relevance signals.", "گزارش برنامه‌ریزی‌شده پیشنهادهای رتبه‌بندی‌شده محصول را برای هر مشتری همراه با شاخص ارتباط ارائه می‌کند."),
    ("PRICE_OPTIMIZATION", "price-optimization", "Price Optimization", "بهینه‌سازی قیمت", False, "date,product_id,unit_price,units_sold,unit_cost,competitor_price,promotion_active", "The beta schema requires historical price, volume, cost, promotion, and competitor context.", "ساختار بتا به تاریخچه قیمت، حجم، هزینه، تخفیف و قیمت رقیب نیاز دارد.", "The planned report shows price sensitivity, margin scenarios, and recommended price ranges.", "گزارش برنامه‌ریزی‌شده حساسیت قیمت، سناریوهای حاشیه سود و بازه قیمت پیشنهادی را نشان می‌دهد."),
)


def seed_documentation(apps, schema_editor):
    Section = apps.get_model("developer_api", "DocumentationSection")
    Page = apps.get_model("developer_api", "DocumentationPage")
    Block = apps.get_model("developer_api", "DocumentationBlock")
    Service = apps.get_model("analytics", "AnalysisService")
    sections = {}
    for slug, title_en, title_fa, order in SECTIONS:
        sections[slug], _ = Section.objects.update_or_create(slug=slug, defaults={"title_en": title_en, "title_fa": title_fa, "display_order": order, "is_active": True})
    for order, (section_slug, slug, title_en, title_fa, summary_en, summary_fa, blocks) in enumerate(GENERAL_PAGES, 1):
        page, _ = Page.objects.update_or_create(slug=slug, defaults={"section": sections[section_slug], "title_en": title_en, "title_fa": title_fa, "summary_en": summary_en, "summary_fa": summary_fa, "display_order": order, "is_active": True})
        Block.objects.filter(page=page).delete()
        for block_order, (kind, heading_en, heading_fa, content_en, content_fa, code, language) in enumerate(blocks, 1):
            Block.objects.create(page=page, kind=kind, heading_en=heading_en, heading_fa=heading_fa, content_en=content_en, content_fa=content_fa, code=code, code_language=language, display_order=block_order)
    for order, (code, slug, title_en, title_fa, active, schema, mapping_en, mapping_fa, report_en, report_fa) in enumerate(SERVICES, 1):
        service = Service.objects.filter(code=code).first()
        page, _ = Page.objects.update_or_create(slug=slug, defaults={"section": sections["analytics-services"], "service": service, "title_en": title_en, "title_fa": title_fa, "summary_en": f"Prepare data, run {title_en}, and interpret every report field.", "summary_fa": f"داده را آماده کنید، {title_fa} را اجرا کنید و همه فیلدهای گزارش را تفسیر کنید.", "display_order": order, "is_active": True})
        Block.objects.filter(page=page).delete()
        Block.objects.create(page=page, kind="CALLOUT", heading_en="Availability", heading_fa="وضعیت دسترسی", content_en="Available now through the dashboard and API." if active else "Private beta. You can upload a representative file and submit it for a secure data review; no analysis credit is consumed.", content_fa="اکنون از طریق داشبورد و API فعال است." if active else "بتای خصوصی. می‌توانید یک فایل نمونه بارگذاری و برای بررسی امن داده ثبت کنید؛ هیچ اعتبار تحلیلی مصرف نمی‌شود.", display_order=1)
        Block.objects.create(page=page, kind="SCHEMA", heading_en="Required CSV structure", heading_fa="ساختار مورد نیاز CSV", content_en=mapping_en, content_fa=mapping_fa, code=schema + "\n" + ",".join("sample" for _ in schema.split(",")), code_language="csv", display_order=2)
        Block.objects.create(page=page, kind="STEPS", heading_en="Tutorial", heading_fa="آموزش گام‌به‌گام", content_en="Export the required fields from your commerce platform\nClean missing identifiers, invalid dates, and non-numeric values\nUpload the file and verify detected columns\nMap every required field to the matching source column\nRun the engine and wait for SUCCESS\nReview summary metrics, charts, detailed rows, and exports" if active else "Export a representative sample using the documented schema\nRemove sensitive columns that are not needed for analysis\nUpload the file through the private-beta service page\nReview and confirm the beta request\nWait for the accounts team to contact you about the isolated trial", content_fa="فیلدهای ضروری را از پلتفرم فروش خروجی بگیرید\nشناسه‌های خالی، تاریخ‌های نامعتبر و مقادیر غیرعددی را پاک‌سازی کنید\nفایل را بارگذاری و ستون‌های شناسایی‌شده را بررسی کنید\nهر فیلد ضروری را به ستون منبع مناسب نگاشت کنید\nموتور را اجرا کنید و تا وضعیت SUCCESS منتظر بمانید\nشاخص‌ها، نمودارها، ردیف‌های تفصیلی و خروجی را بررسی کنید" if active else "یک نمونه نماینده با ساختار مستندشده خروجی بگیرید\nستون‌های حساس و غیرضروری را حذف کنید\nفایل را در صفحه سرویس بتای خصوصی بارگذاری کنید\nدرخواست بتا را بررسی و تأیید کنید\nمنتظر تماس تیم حساب‌ها برای اجرای آزمایشی مجزا باشید", display_order=3)
        if active:
            Block.objects.create(page=page, kind="CODE", heading_en="Start through the API", heading_fa="اجرا از طریق API", content_en="Upload the file first, then submit the service-specific mapping to the returned project ID.", content_fa="ابتدا فایل را بارگذاری کنید و سپس نگاشت مخصوص سرویس را برای شناسه پروژه بازگشتی ارسال کنید.", code=f"curl -X POST http://localhost:8000/api/v1/projects/upload/ \\\n+  -H \"X-API-Key: $MLAAS_API_KEY\" \\\n+  -F \"file=@dataset.csv\" \\\n+  -F \"title={title_en} report\" \\\n+  -F \"analysis_type={code}\"\n\n# Then start the returned project\ncurl -X POST http://localhost:8000/api/v1/projects/$PROJECT_ID/start/ \\\n+  -H \"X-API-Key: $MLAAS_API_KEY\" \\\n+  -H \"Content-Type: application/json\" \\\n+  -d '{{\"mapping\":{{}}}}'", code_language="bash", display_order=4)
        Block.objects.create(page=page, kind="REPORT", heading_en="What the report shows", heading_fa="گزارش چه چیزی نشان می‌دهد", content_en=report_en, content_fa=report_fa, display_order=5)


class Migration(migrations.Migration):
    dependencies = [("developer_api", "0003_documentationsection_documentationpage_and_more")]
    operations = [migrations.RunPython(seed_documentation, migrations.RunPython.noop)]
